//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreAPI.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookStore
    {
        public int id { get; set; }
        public string name_book { get; set; }
        public Nullable<int> price { get; set; }
        public string picture { get; set; }
    }
}
